//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWhiteWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee : Person
    {
        public Employee()
        {
            this.CLOUs = new HashSet<CLOU>();
            this.Tickets = new HashSet<Ticket>();
            this.SupportEvents = new HashSet<SupportEvent>();
        }
    
        public int EmployeeTypeId { get; set; }
        public string SSN { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual ICollection<CLOU> CLOUs { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
    }
}
