//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWhiteWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int Id { get; set; }
        public string AreaCode { get; set; }
        public string Number { get; set; }
        public string Ext { get; set; }
        public int PhoneNumberTypeId { get; set; }
    
        public virtual PhoneNumberType PhoneNumberType { get; set; }
    }
}
