//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWhiteWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportEvent
    {
        public SupportEvent()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int SupportEventId { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int TicketId { get; set; }
        public string Description { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
