//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWhiteWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.SupportEvents = new HashSet<SupportEvent>();
        }
    
        public int TicketId { get; set; }
        public System.DateTime DateOpened { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }
        public int AccountId { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<SupportEvent> SupportEvents { get; set; }
        public virtual Account Account { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
